### ISSUE TITLE
Resna is sending wrong reports for native ads

### ISSUE THREAD

**Issue by m98** [oddrun/resana-android-sdk#2]
Resana is sending landing click and view reports for native advertisement which does not have landing images.

I guess the report function should not be called in that situation. 

Maybe [here](https://github.com/oddrun/resana-android-sdk/blob/2903239202866ad77ad13c79ae14bf70653167c8/resana/src/main/java/io/resana/ResanaInternal.java#L251) is the problem:
`nativeProvider.handleLandingClick(context, ad);`

**Comment by ehsansouri23** [comment]
bug fixed. 
thanks for reporting!
